require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Dimand' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-image-crop-picker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'react-native-appearance', :path => '../node_modules/react-native-appearance'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'

  pod 'paytm-customuisdk-react-native', :path => '../node_modules/paytm-customuisdk-react-native'

  target 'DimandTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end