export const MyLanguage = {
    'en':{
        welcome:"Welcome",
        homelabel1:"What are you looking for ?",
        homelabel2:"Search by category",
        homelabel3:"Recommended Jobs",
        postedon:"posting time :",
        active:"Active",
        closed:"Closed",
        urgenthiring:"Urgent Hiring",
        applynow:"Apply Now",
        backhandlerstatement:"press back again to exit the app",
        backhandlertitle:"Exit",
        filter:"Filter",
        clearfilters:"Clear Filters",
        category:"Category",
        salary:"Salary",
        companysize:"Company Size",
        location:"Location",
        apply:"Apply",
        nothingfoundforresult:"Nothing found for search result",
        trysomethingelse:"try something else",
        freelancerjobs:"Freelancer Jobs",
        freelancerjob:"Freelancer Job",
        settings:"Settings",
        aboutus:"About Us",
        contactus:"Contact Us",
        privacypolicy:"Privacy Policy",
        termsandcondition:"Terms and Condition",
        rateapp:"Rate App",
        appliedjobs:"Applied Jobs",
        submit:"Submit",
        confirmation:"Confirmation",
        jobapplysuccessmsg:"successfully applied for this job",
        applymore:"Apply More",
        nojobsfound:"No Jobs Found...",
        nofilteredjobsfound:"No Filtered Jobs Found...",
        nojobsapplied:"No Jobs Applied ...",
        profile:"Profile",
        everyweektogglesoff:"Every week toggles off",
        savedjob:"Saved Job",
        appliedjob:"Applied Job",
        appliedon:"Applied on",
        personaldetails:"Personal Details",
        firstname:"First Name",
        lastname:"Last Name",
        emailid:"Email ID",
        mobilenumber:"Mobile Number",
        address:"Address",
        currentcity:"Current City",
        state:"State",
        language:"Language",
        expertise:"Expertise",
        companydetails:"Company Details",
        knowyourcustomer:"Know your Customer",
        kycministatement:"Upload the following documents to get verified user badge",
        aadharcard:"Aadhar Card",
        pancard:"Pan Card",
        saveprofile:"Save Profile",
        logout:"Logout",
        jobactivated:"Job Activated",
        jobdeactivated:"Job Deactivated",
        jobdeleted:"Job Deleted",
        nointernetconnection:"No Internet Connection",
        pleasecheckyourinternet:"please check your device connection",
        servererror500:"Server Error : 500",
        somethingwentwrong:"Something went wrong ....",
        jobsaved:"Job Saved",
        jobunsaved:"Job Unsaved",
        apistatus0:"Api Status : 0",
        applyfailed:"Apply Failed",
        previousjobinfo:"Previous Job Info",
        jobtitle:"Job Title",
        companyname:"Company Name",
        experience:"Experience",
        description:"Description",
        jobtype:"Job Type",
        employeerole:"Employee Role",
        skills:"Skills",
        qualification:"Qualification",
        vacancy:"Vacancy",
        expertiseupdated:"Expertise Updated",
        expertiseadded:"Expertise Added",
        profilesaved:"Profile Saved",
        companyexperienceupdatefailed:"Company Experience Update Failed",
        companyexperienceupdatesuccess:"Company Experience Updated",
        companyexperienceaddingfailed:"Company Experience Adding Failed",
        companyexperienceaddingsuccess:"Company Experience Added",
        approvalpending:"Approval Pending",
        approved:"Approved",
        rejected:"Rejected",
        loading:"Loading...",
        update:"Update",
        companyprofile:"Company Profile",
        workexperience:"Work Experience",
        lastjobtitle:"Last Job Title",
        lastjobexp:"Last Job Experience",
        lastjobtimestamps:"Last Job Timestamps",
        startdate:"Start Date",
        enddate:"End Date",
        totalexp:"Total Experience",
        adddetails:"Add Details",
        updatedetails:"Update Details",
        addexpertise:"Add Expertise",
        updateexpertise:"Update Expertise",
        selectatleastonecategory:"Select Atleast One Category",
        select2photos:"Select 2 Photos",
        aadharmustcontain2:"Aadhar must contain 2 photos !",
        companynameblank:"Company Name cannot be blank",
        workexperienceblank:"Work Experience cannot be blank",
        jobtitleblank:"Job title cannot be blank",
        jobexpblank:"Job Experience cannot be blank",
        startdateblank:"Start Date cannot be blank",
        startdateinvalid:"Start Date Invalid",
        enddateblank:"End Date cannot be blank",
        enddateinvalid:"End Date Invalid",
        totalexpblank:"Total Experience cannot be blank",
        cancel:"Cancel",
        tryagain:"Try Again",
        jobdeletefailed:"Job Delete Failed",
        deletepost:"Delete Post",
        wanttodelete:"want to delete this job post ?",
        no:"No",
        yes:"Yes",
        status:"Status :",
        home:"Home",
        activepost:"Active Post",
        todayapplieduser:"Today's\nApplied User",
        totalpost:"Total Post",
        jobrecruitmentclose:"Job Recruitment Closed",
        deactivatepost:"Deactivate Post",
        wanttodeactivate:"want to deactivate this job post ?",
        closerecruitment:"Close Recruitment",
        wanttocloserecruit:"want to close recruitment this job post ?",
        activejobs:"Active Jobs",
        employeeapplied:"Employee Applied",
        alljobs:"All Jobs",
        activatepost:"Activate Post",
        wanttoactivatepost:"want to activate this job post ?",
        addpost:"Add Post",
        jobcreatedsuccess:"Job Created Successfully",
        freelancetitleblank:"Freelance Title cannot be blank",
        imageblank:"Image cannot be blank",
        longitudeerror:"Longitude Error",
        latitudeerror:"Latitude Error",
        locationblank:"Location cannot be blank",
        vacancyblank:"Vacancy cannot be blank",
        qualificationblank:"Qualification cannot be blank",
        employmentskillblank:"Employment Skill cannot be blank",
        employementrolaeblank:"Employment Role cannot be blank",
        jobdescblank:"Job Description cannot be blank",
        jobshortdescblank:"Short Job Description cannot be blank",
        salaryblank:"Salary cannot be blank",
        experienceblank:"Experience cannot be blank",
        postjob:"Post Job",
        jobtitledesignation:"Job Title (Designation)",
        shortjobdescription:"Short Job Description",
        jobdescription:"Job Description",
        employmenttype:"Employment Type",
        fulltime:"Full Time",
        parttime:"Part Time",
        employmentrole:"Employment Role",
        employmentskills:"Employment Skills",
        googlelocation:"Google Location",
        joblocation:"Job Location",
        chooseimage:"Choose Image",
        urgentjob:"Urgent Job",
        freelancerjob:"Freelancer Job",
        freelancertitle:"Freelancer Title",
        freelancetime:"Freelance Time (Days)",
        enterdaysofjobhere:"Enter Days of Job here",
        email:"Email",
        mobile:"Mobile",
        appliedemployees:"Applied Employees",
        currentjobstatus:"Current Job Status",
        applieddate:"Applied Date",
        noemployeesapplied:"No Employees Applied...",
        noemployeesfound:"No Employees Found...",
        filteredemployees:"Filtered Employees",
        name:"Name",
        companydescription:"Company Description",
        companystrength:"Company Strength",
        numberofemployees:"Number of Employees",
        website:"Website",
        companywebsite:"Company Website",
        productwishlisted:"Product Wishlisted",
        productremovedfromwishlist:"Product removed from wishlist",
        searchyourproduct:"Search Your Product",
        categories:"Categories",
        seeall:"see all",
        featured:"Featured",
        bestsellers:"Best Sellers",
        mycart:"My Cart",
        favourite:"Favourite",
        myorders:"My Orders",
        productsaved:"Product Saved",
        productunsaved:"Product Unsaved",
        noproductfound:"No Product Found...",
        searchproduct:"Search Product",
        productremovedfromcart:"Product removed from cart",
        productremovefailed:"Product removal failed",
        cart:"Cart",
        continue:"Continue",
        allcategories:"All Categories",
        nocategoriesfound:"No Categories Found...",
        checkout:"Checkout",
        number:"Number",
        city:"City",
        subtotal:"Subtotal",
        shipping:"Shipping",
        total:"Total",
        buy:"Buy",
        nameblank:"Name cannot be blank",
        addressblank:"Address cannot be blank",
        cityblank:"City cannot be blank",
        stateblank:"State cannot be blank",
        postalblank:"Postal Code cannot be blank",
        phonenumberblank:"Phone Number cannot be blank",
        postal:"Postal Code",
        phonenumber:"Phone Number",
        makedefault:"Make Default",
        addaddress:"Add Address",
        updateaddress:"Update Address",
        productwishlistremovefailed:"Product removal from wishlist failed",
        noproductwishlisted:"No Product Wishlisted...",
        noordersplacedyet:"No Orders Placed Yet...",
        orderagain:"Order Again",
        notifications:"Notifications",
        nonewnotifications:"No New Notifications...",
        youhavesuccessfully:"you have successfully",
        completedyourpaymentprocedure:"completed your payment procedure",
        trackorder:"Track Order",
        backtohome:"Back To Home",
        productaddedtocart:"Product added to cart",
        productalreadyaddedincart:"Product already added in cart",
        productaddingtocartfailed:"Product adding to cart failed",
        buynow:"Buy Now",
        addtocart:"Add To Cart",
        back:"Back",
        reviews:"Reviews",
        aboutthecompany:"About The Company",
        yearofestablistment:"Year Of Establisment",
        profileupdated:"Profile Updated",
        profileupdatefailed:"Profile Update Failed",
        productdetails:"Product Details",
        editprofile:"Edit Profile",
        shippingaddress:"Shipping Address",
        wishlist:"Wishlist",
        orderhistory:"Order History",
        paymentoption:"Payment Option",
        addressdeleted:"Address Deleted",
        deleteaddress:"Delete Address",
        wantodeleteaddress:"want to delete this address ?",
        trackorders:"Track Orders",
        products:"Products",
        details:"Details",




      },

      'hi':{
        welcome:"स्वागत हे",
        homelabel1:"आप क्या ढूंढ रहे हैं ?",
        homelabel2:"श्रेणी के अनुसार खोजें",
        homelabel3:"अनुशंसित नौकरियां",
        postedon:"पोस्टिंग समय :",
        active:"सक्रिय",
        closed:"बंद",
        urgenthiring:"तत्काल भर्ती",
        applynow:"अभी अप्लाई करें",
        backhandlerstatement:"ऐप से निकलने के लिए फिर से दबाएं",
        backhandlertitle:"बाहर जाएं",
        filter:"फ़िल्टर",
        clearfilters:"फ़िल्टर साफ़ करें",
        category:"वर्ग",
        salary:"वेतन",
        companysize:"कंपनी का आकार",
        location:"स्थान",
        apply:"लागू",
        nothingfoundforresult:"खोज परिणाम के लिए कुछ नहीं मिला",
        trysomethingelse:"कुछ और कोशिश करो",
        freelancerjobs:"फ्रीलांसर नौकरियां",
        freelancerjob:"फ्रीलांसर नौकरि",
        settings:"सेटिंग",
        aboutus:"हमारे बारे में",
        contactus:"संपर्क करें",
        privacypolicy:"गोपनीयता नीति",
        termsandcondition:"नियम व शर्तें",
        rateapp:"हमें रेटिंग दें",
        appliedjobs:"एप्लाइड जॉब्स",
        submit:"प्रस्तुत",
        confirmation:"पुष्टीकरण",
        jobapplysuccessmsg:"इस नौकरी के लिए सफलतापूर्वक आवेदन किया",
        applymore:"अधिक आवेदन करें",
        nojobsfound:"कोई नौकरी नहीं मिली...",
        nofilteredjobsfound:"कोई फ़िल्टर्ड नौकरी नहीं मिली...",
        nojobsapplied:"कोई नौकरी नहीं मिली...",
        profile:"प्रोफ़ाइल",
        everyweektogglesoff:"हर हफ्ते बंद हो जाता है",
        savedjob:"सहेजी गई जॉब",
        appliedjob:"एप्लाइड जॉब",
        appliedon:"आवेदन का समय",
        personaldetails:"व्यक्तिगत विवरण",
        firstname:"प्रथम नाम",
        lastname:"पिछल नाम",
        emailid:"ईमेल आईडी",
        mobilenumber:"मोबाइल नंबर",
        address:"पता",
        currentcity:"वर्तमान शहर",
        state:"राज्य",
        language:"भाषा",
        expertise:"विशेषज्ञता",
        companydetails:"कंपनी का विवरण",
        knowyourcustomer:"अपने ग्राहक को जानो",
        kycministatement:"सत्यापित उपयोगकर्ता बैज प्राप्त करने के लिए निम्नलिखित दस्तावेज़ अपलोड करें",
        aadharcard:"आधार कार्ड",
        pancard:"पण कार्ड",
        saveprofile:"प्रोफाइल सेव करें",
        logout:"लॉग आउट",
        jobactivated:"नौकरी सक्रिय",
        jobdeactivated:"नौकरी निष्क्रिय",
        jobdeleted:"नौकरी हटा दी गई",
        nointernetconnection:"कोई इंटरनेट कनेक्शन नहीं",
        pleasecheckyourinternet:"कृपया अपने इंटरनेट कनेक्शन की जाँच करें",
        servererror500:"सर्वर त्रुटि: 500",
        somethingwentwrong:"कुछ गलत हो गया ....",
        jobsaved:"नौकरी बचाई",
        jobunsaved:"कार्य सहेजा नहीं गया",
        apistatus0:"एपीआई स्थिति: 0",
        applyfailed:"आवेदन विफल",
        previousjobinfo:"पिछली नौकरी की जानकारी",
        jobtitle:"नौकरी का नाम",
        companyname:"कंपनी का नाम",
        experience:"अनुभव",
        description:"विवरण",
        jobtype:"नौकरी का प्रकार",
        employeerole:"कर्मचारी भूमिका",
        skills:"कौशल",
        qualification:"योग्यता",
        vacancy:"रिक्ति",
        expertiseupdated:"विशेषज्ञता अद्यतन",
        expertiseadded:"विशेषज्ञता जोड़ी गई",
        profilesaved:"प्रोफ़ाइल सहेजी गई",
        companyexperienceupdatefailed:"कंपनी अनुभव अपडेट विफल",
        companyexperienceupdatesuccess:"कंपनी का अनुभव अपडेट किया गया",
        companyexperienceaddingfailed:"कंपनी का अनुभव जोड़ने में विफल",
        companyexperienceaddingsuccess:"कंपनी का अनुभव जोड़ा गया",
        approvalpending:"स्वीकृति लंबित",
        approved:"मंजूर",
        rejected:"अस्वीकृत",
        loading:"लोड हो रहा है...",
        update:"अपडेट ",
        companyprofile:"कंपनी प्रोफाइल",
        workexperience:"कार्य अनुभव",
        lastjobtitle:"अंतिम नौकरी शीर्षक",
        lastjobexp:"अंतिम नौकरी का अनुभव",
        lastjobtimestamps:"अंतिम कार्य टाइमस्टैम्प",
        startdate:"आरंभ की तारीख",
        enddate:"समाप्ति तारीख",
        totalexp:"कुल अनुभव",
        adddetails:"विवरण जोड़ें",
        updatedetails:"विवरण अपडेट करें",
        addexpertise:"विशेषज्ञता जोड़ें",
        updateexpertise:"विशेषज्ञता अपडेट करें",
        selectatleastonecategory:"कम से कम एक श्रेणी का चयन करें",
        select2photos:"2 तस्वीरें चुनें",
        aadharmustcontain2:"आधार में 2 फोटो होने चाहिए !",
        companynameblank:"कंपनी का नाम खाली नहीं हो सकता",
        workexperienceblank:"कार्य अनुभव रिक्त नहीं हो सकता",
        jobtitleblank:"नौकरी का शीर्षक खाली नहीं हो सकता",
        jobexpblank:"नौकरी का अनुभव खाली नहीं हो सकता",
        startdateblank:"प्रारंभ तारीख रिक्त नहीं हो सकती",
        startdateinvalid:"प्रारंभ दिनांक अमान्य",
        enddateblank:"समाप्ति तारीख खाली नहीं हो सकती",
        enddateinvalid:"समाप्ति तारीख अमान्य",
        totalexpblank:"कुल अनुभव खाली नहीं हो सकता",
        cancel:"रद्द करें",
        tryagain:"पुनः प्रयास करें",
        jobdeletefailed:"नौकरी हटाना विफल",
        deletepost:"पोस्ट को हटाएं",
        wanttodelete:"इस जॉब पोस्ट को हटाना चाहते हैं ?",
        no:"नहीं",
        yes:"हाँ",
        status:"स्थिति :",
        home:"घर",
        activepost:"सक्रिय पोस्ट",
        todayapplieduser:"आज का\nअनुप्रयुक्त उपयोगकर्ता",
        totalpost:"कुल पोस्ट",
        jobrecruitmentclose:"नौकरी भर्ती बंद",
        deactivatepost:"पोस्ट निष्क्रिय",
        wanttodeactivate:"इस जॉब पोस्ट को निष्क्रिय करना चाहते हैं?",
        closerecruitment:"भर्ती बंद करें",
        wanttocloserecruit:"इस नौकरी पद की भर्ती बंद करना चाहते हैं?",
        activejobs:"सक्रिय नौकरियां",
        employeeapplied:"कर्मचारी लागू",
        alljobs:"सारी नौकरियां",
        activatepost:"पोस्ट सक्रिय",
        wanttoactivatepost:"इस जॉब पोस्ट को सक्रिय करना चाहते हैं ?",
        addpost:"पोस्ट जोड़ें",
        jobcreatedsuccess:"नौकरी सफलतापूर्वक बनाई गई",
        freelancetitleblank:"फ्रीलांस शीर्षक खाली नहीं हो सकता",
        imageblank:"छवि खाली नहीं हो सकती",
        longitudeerror:"देशांतर त्रुटि",
        latitudeerror:"अक्षांश त्रुटि",
        locationblank:"स्थान रिक्त नहीं हो सकता",
        vacancyblank:"रिक्ति खाली नहीं हो सकती",
        qualificationblank:"योग्यता खाली नहीं हो सकती",
        employmentskillblank:"रोजगार कौशल खाली नहीं हो सकता",
        employementrolaeblank:"रोजगार भूमिका खाली नहीं हो सकती",
        jobdescblank:"नौकरी का विवरण खाली नहीं हो सकता",
        jobshortdescblank:"लघु कार्य विवरण रिक्त नहीं हो सकता",
        salaryblank:"वेतन खाली नहीं हो सकता",
        experienceblank:"अनुभव खाली नहीं हो सकता",
        postjob:"नौकरी पोस्ट करें",
        jobtitledesignation:"नौकरी का शीर्षक (पदनाम)",
        shortjobdescription:"लघु नौकरी विवरण",
        jobdescription:"नौकरी का विवरण",
        employmenttype:"रोजगार के प्रकार",
        fulltime:"पूरा समय",
        parttime:"पार्ट टाईम",
        employmentrole:"रोजगार भूमिका",
        employmentskills:"रोजगार कौशल",
        googlelocation:"गूगल स्थान",
        joblocation:"नौकरी करने का स्थान",
        chooseimage:"छवि चुनें",
        urgentjob:"तत्काल नौकरी",
        freelancerjob:"फ्रीलांसर जॉब",
        freelancertitle:"फ्रीलांसर शीर्षक",
        freelancetime:"फ्रीलांस समय (दिन)",
        enterdaysofjobhere:"यहां नौकरी के दिन दर्ज करें",
        email:"ईमेल",
        mobile:"मोबाइल",
        appliedemployees:"लागू कर्मचारी",
        currentjobstatus:"वर्तमान नौकरी की स्थिति",
        applieddate:"लागू तिथि",
        noemployeesapplied:"किसी कर्मचारी ने आवेदन नहीं किया...",
        noemployeesfound:"कोई कर्मचारी नहीं मिला...",
        filteredemployees:"फ़िल्टर किए गए कर्मचारी",
        name:"नाम",
        companydescription:"कंपनी विवरण",
        companystrength:"कंपनी की ताकत",
        numberofemployees:"कर्मचारियों की संख्या",
        website:"वेबसाइट",
        companywebsite:"कंपनी की वेबसाइट",
        productwishlisted:"उत्पाद विशलिस्टेड",
        productremovedfromwishlist:"उत्पाद को इच्छा सूची से हटाया गया",
        searchyourproduct:"अपना उत्पाद खोजें",
        categories:"श्रेणियाँ",
        seeall:"सभी देखें",
        featured:"विशेष रुप से प्रदर्शित",
        bestsellers:"सर्वाधिक बिकाऊ",
        mycart:"मेरी गाड़ी",
        favourite:"पसंदीदा",
        myorders:"मेरे आदेश",
        productsaved:"उत्पाद सहेजा गया",
        productunsaved:"उत्पाद सहेजा नहीं गया",
        noproductfound:"कोई उत्पाद नहीं मिला...",
        searchproduct:"उत्पाद खोजें",
        productremovedfromcart:"कार्ट से निकाला गया उत्पाद",
        productremovefailed:"उत्पाद निकालना विफल",
        cart:"कार्ट",
        continue:"जारी रखें",
        allcategories:"सब वर्ग",
        nocategoriesfound:"कोई श्रेणी नहीं मिली...",
        checkout:"चेक आउट",
        number:"नंबर",
        city:"शहर",
        subtotal:"उप-योग",
        shipping:"शिपिंग",
        total:"संपूर्ण",
        buy:"खरीद",
        nameblank:"नाम खाली नहीं हो सकता",
        addressblank:"पता खाली नहीं हो सकता",
        cityblank:"शहर खाली नहीं हो सकता",
        stateblank:"राज्य खाली नहीं हो सकता",
        postalblank:"पोस्टल कोड खाली नहीं हो सकता",
        phonenumberblank:"फ़ोन नंबर खाली नहीं हो सकता",
        postal:"डाक कोड",
        phonenumber:"फ़ोन नंबर",
        makedefault:"डिफ़ॉल्ट बनाना",
        addaddress:"पता जोड़ें",
        updateaddress:"पता अपडेट करें",
        productwishlistremovefailed:"इच्छा सूची से उत्पाद निकालना विफल रहा",
        noproductwishlisted:"कोई उत्पाद विशलिस्टेड नहीं...",
        noordersplacedyet:"अभी तक कोई आदेश नहीं आया...",
        orderagain:"फिर से ऑर्डर करें",
        notifications:"सूचनाएं",
        nonewnotifications:"कोई नए संदेश नहीं...",
        youhavesuccessfully:"आपने सफलतापूर्वक",
        completedyourpaymentprocedure:"आपकी भुगतान प्रक्रिया पूरी की",
        trackorder:"ऑर्डर पर नज़र रखें",
        backtohome:"घर वापिस जा रहा हूँ",
        productaddedtocart:"कार्ट में जोड़ा गया उत्पाद",
        productalreadyaddedincart:"उत्पाद कार्ट में पहले ही जोड़ा जा चुका है",
        productaddingtocartfailed:"कार्ट में उत्पाद जोड़ने में विफल रहा",
        buynow:"अभी खरीदें",
        addtocart:"कार्ट में जोड़ें",
        back:"वापस",
        reviews:"समीक्षा",
        aboutthecompany:"कंपनी के बारे में",
        yearofestablistment:"स्थापना का वर्ष",
        profileupdated:"प्रोफ़ाइल अपडेट",
        profileupdatefailed:"प्रोफ़ाइल अपडेट विफल",
        productdetails:"उत्पाद विवरण",
        editprofile:"प्रोफ़ाइल संपादित करें",
        shippingaddress:"शिपिंग पता",
        wishlist:"इच्छा-सूची",
        orderhistory:"आदेश इतिहास",
        paymentoption:"भुगतान विकल्प",
        addressdeleted:"पता हटाया गया",
        deleteaddress:"पता हटाएं",
        wantodeleteaddress:"इस पते को हटाना चाहते हैं?",
        trackorders:"ट्रैक ऑर्डर",
        products:"उत्पादों",
        details:"विवरण",

    },

    'gj':{
        welcome:"સ્વાગત છે",
        homelabel1:"તમે શું શોધી રહ્યા છો?",
        homelabel2:"કેટેગરી પ્રમાણે શોધો",
        homelabel3:"ભલામણ નોકરીઓ",
        postedon:"પોસ્ટિંગ સમય:",
        active:"સક્રિય",
        closed:"બંધ",
        urgenthiring:"અર્જન્ટ હાયરિંગ",
        applynow:"અરજી કરો",
        backhandlerstatement:"એપ માંથી બહાર નીકળવા માટે ફરીથી પાછા દબાવો",
        backhandlertitle:"બહાર નીકળો",
        filter:"ફિલ્ટર",
        clearfilters:"ગાળકો સાફ કરો",
        category:"કેટેગરી",
        salary:"પગાર",
        companysize:"કંપનીનું કદ",
        location:"સ્થાન",
        apply:"લાગુ કરો",
        nothingfoundforresult:"શોધ પરિણામ માટે કંઈ મળ્યું નથી",
        trysomethingelse:"બીજું કંઈક અજમાવો",
        freelancerjobs:"ફ્રીલાન્સ નોકરીઓ",
        freelancerjob:"ફ્રીલાન્સ નોકરી",
        settings:"સેટિંગ્સ",
        aboutus:"અમારા વિશે",
        contactus:"અમારો સંપર્ક કરો",
        privacypolicy:"ગોપનીયતા નીતિ",
        termsandcondition:"નિયમો અને શરતો",
        rateapp:"રેટિંગ આપો",
        appliedjobs:"એપ્લાઇડ જોબ્સ",
        submit:"સબમિટ કરો",
        confirmation:"પુષ્ટિ",
        jobapplysuccessmsg:"સફળતાપૂર્વક આ નોકરી માટે અરજી કરી",
        applymore:"વધુ લાગુ કરો",
        nojobsfound:"કોઈ જોબ મળી નથી ...",
        nofilteredjobsfound:"કોઈ ફિલ્ટર કરેલી જોબ મળી નથી ...",
        nojobsapplied:"કોઈ જોબ મળી નથી ...",
        profile:"પ્રોફાઇલ",
        everyweektogglesoff:"દર અઠવાડિયે બંધ થાય છે",
        savedjob:"સાચવેલ જોબ",
        appliedjob:"એપ્લાઇડ જોબ",
        appliedon:"અરજીનો સમય",
        personaldetails:"અંગત વિગતો",
        firstname:"પ્રથમ નામ",
        lastname:"છેલ્લું નામ",
        emailid:"ઇમેઇલ આઈડી",
        mobilenumber:"મોબાઇલ નંબર",
        address:"સરનામું",
        currentcity:"વર્તમાન શહેર",
        state:"રાજ્ય",
        language:"ભાષા",
        expertise:"કુશળતા",
        companydetails:"કંપની વિગતો",
        knowyourcustomer:"તમારા ગ્રાહકને જાણો",
        kycministatement:"ચકાસાયેલ વપરાશકર્તા બેજ મેળવવા માટે નીચેના દસ્તાવેજો અપલોડ કરો",
        aadharcard:"આધારકાર્ડ",
        pancard:"પાન કાર્ડ",
        saveprofile:"પ્રોફાઇલ સાચવો",
        logout:"લૉગ આઉટ",
        jobactivated:"જોબ સક્રિય",
        jobdeactivated:"જોબ નિષ્ક્રિય",
        jobdeleted:"જોબ કાઢી",
        nointernetconnection:"ઇન્ટરનેટ કનેક્શન નથી",
        pleasecheckyourinternet:"કૃપા કરીને તમારું ઇન્ટરનેટ કનેક્શન તપાસો",
        servererror500:"સર્વર ભૂલ: 500",
        somethingwentwrong:"કંઈક ખોટું થયું ....",
        jobsaved:"જોબ સાચવી",
        jobunsaved:"જોબ વણસાચવેલી",
        apistatus0:"એપીઆઇ સ્થિતિ: 0",
        applyfailed:"અરજી નિષ્ફળ",
        previousjobinfo:"પહેલાની જોબ માહિતી",
        jobtitle:"જોબ શીર્ષક",
        companyname:"કંપની નું નામ",
        experience:"અનુભવ",
        description:"વર્ણન",
        jobtype:"જોબનો પ્રકાર",
        employeerole:"કર્મચારીની ભૂમિકા",
        skills:"કુશળતા",
        qualification:"લાયકાત",
        vacancy:"ખાલી જગ્યા",
        expertiseupdated:"કુશળતા અપડેટ",
        expertiseadded:"કુશળતા ઉમેરવામાં",
        profilesaved:"પ્રોફાઇલ સાચવેલ",
        companyexperienceupdatefailed:"કંપની અનુભવ અપડેટ નિષ્ફળ",
        companyexperienceupdatesuccess:"કંપનીનો અનુભવ અપડેટ થયો",
        companyexperienceaddingfailed:"કંપનીનો અનુભવ ઉમેરવામાં નિષ્ફળ",
        companyexperienceaddingsuccess:"કંપનીનો અનુભવ ઉમેર્યો",
        approvalpending:"મંજૂરી બાકી",
        approved:"મંજુર",
        rejected:"નકારી",
        loading:"લોડ કરી રહ્યું છે...",
        update:"અપડેટ",
        companyprofile:"કંપની પ્રોફાઇલ",
        workexperience:"કાર્ય અનુભવ",
        lastjobtitle:"છેલ્લું જોબ શીર્ષક",
        lastjobexp:"છેલ્લું જોબ અનુભવ",
        lastjobtimestamps:"છેલ્લું જોબ ટાઇમસ્ટેમ્પ",
        startdate:"પ્રારંભ તારીખ",
        enddate:"અંતિમ તારીખ",
        totalexp:"કુલ અનુભવ",
        adddetails:"વિગતો ઉમેરો",
        updatedetails:"અપડેટ વિગતો",
        addexpertise:"કુશળતા ઉમેરો",
        updateexpertise:"કુશળતા સુધારો",
        selectatleastonecategory:"એટલાસ્ટ વન કેટેગરી પસંદ કરો",
        select2photos:"2 ફોટા પસંદ કરો",
        aadharmustcontain2:"આધારમાં 2 ફોટા હોવા જોઈએ!",
        companynameblank:"કંપનીનું નામ ખાલી હોઈ શકતું નથી",
        workexperienceblank:"કામનો અનુભવ ખાલી હોઈ શકતો નથી",
        jobtitleblank:"જોબનું શીર્ષક ખાલી હોઈ શકતું નથી",
        jobexpblank:"નોકરીનો અનુભવ ખાલી હોઈ શકતો નથી",
        startdateblank:"પ્રારંભ તારીખ ખાલી હોઈ શકતી નથી",
        startdateinvalid:"પ્રારંભ તારીખ અમાન્ય છે",
        enddateblank:"અંતિમ તારીખ ખાલી હોઈ શકતી નથી",
        enddateinvalid:"અંતિમ તારીખ અમાન્ય છે",
        totalexpblank:"કુલ અનુભવ ખાલી હોઈ શકતો નથી",
        cancel:"રદ કરો",
        tryagain:"ફરીથી પ્રયત્ન કરો",
        jobdeletefailed:"જોબ ડિલીટ નિષ્ફળ",
        deletepost:"પોસ્ટ કા deleteી નાખો",
        wanttodelete:"શું તમે આ જોબ પોસ્ટને કા deleteી નાખવા માંગો છો?",
        no:"ના",
        yes:"હા",
        status:"સ્થિતિ :",
        home:"ઘર",
        activepost:"સક્રિય પોસ્ટ",
        todayapplieduser:"આજનો \ n લાગુ કરાયેલ વપરાશકર્તા",
        totalpost:"કુલ પોસ્ટ",
        jobrecruitmentclose:"જોબ ભરતી ક્લોસેડોસ્ટ",
        deactivatepost:"નિષ્ક્રિય પોસ્ટ",
        wanttodeactivate:"આ જોબ પોસ્ટને નિષ્ક્રિય કરવા માંગો છો?",
        closerecruitment:"ભરતી બંધ કરો",
        wanttocloserecruit:"આ નોકરી પોસ્ટ ભરતી બંધ કરવા માંગો છો?",
        activejobs:"સક્રિય નોકરીઓ",
        employeeapplied:"કર્મચારીએ અરજી કરી",
        alljobs:"બધી નોકરીઓ",
        activatepost:"સક્રિય કરો પોસ્ટ",
        wanttoactivatepost:"આ નોકરી પોસ્ટ સક્રિય કરવા માંગો છો?",
        addpost:"પોસ્ટ ઉમેરો",
        jobcreatedsuccess:"જોબ સફળતાપૂર્વક બનાવેલ છે",
        freelancetitleblank:"ફ્રીલાન્સ શીર્ષક ખાલી હોઈ શકતું નથી",
        imageblank:"છબી ખાલી હોઈ શકતી નથી",
        longitudeerror:"રેખાંશ ભૂલ",
        latitudeerror:"અક્ષાંશ ભૂલ",
        locationblank:"સ્થાન ખાલી હોઈ શકતું નથી",
        vacancyblank:"ખાલી જગ્યા ખાલી રહી શકાતી નથી",
        qualificationblank:"લાયકાત ખાલી હોઈ શકતી નથી",
        employmentskillblank:"રોજગાર કૌશલ્ય ખાલી હોઈ શકતું નથી",
        employementrolaeblank:"રોજગારની ભૂમિકા ખાલી હોઈ શકતી નથી",
        jobdescblank:"જોબનું વર્ણન ખાલી હોઈ શકતું નથી",
        jobshortdescblank:"ટૂંકી જોબનું વર્ણન ખાલી હોઈ શકતું નથી",
        salaryblank:"પગાર ખાલી હોઈ શકતો નથી",
        experienceblank:"અનુભવ ખાલી હોઈ શકતો નથી",
        postjob:"પોસ્ટ જોબ",
        jobtitledesignation:"જોબ શીર્ષક (હોદ્દો)",
        shortjobdescription:"ટૂંકી જોબ વર્ણન",
        jobdescription:"કામનું વર્ણન",
        employmenttype:"કામદારનો પ્રકાર",
        fulltime:"આખો સમય",
        parttime:"ભાગ સમય",
        employmentrole:"રોજગાર ભૂમિકા",
        employmentskills:"રોજગાર કુશળતા",
        googlelocation:"ગૂગલ લોકેશન",
        joblocation:"જોબ સ્થાન",
        chooseimage:"છબી પસંદ કરો",
        urgentjob:"અર્જન્ટ જોબ",
        freelancerjob:"ફ્રીલાન્સ જોબ",
        freelancertitle:"ફ્રીલાન્સ શીર્ષક",
        freelancetime:"ફ્રીલાન્સ સમય (દિવસો)",
        enterdaysofjobhere:"નોકરીના દિવસો અહીં દાખલ કરો",
        email:"ઇમેઇલ",
        mobile:"મોબાઇલ",
        appliedemployees:"એપ્લાઇડ કર્મચારી",
        currentjobstatus:"વર્તમાન જોબ સ્થિતિ",
        applieddate:"લાગુ તારીખ",
        noemployeesapplied:"કોઈ કર્મચારી લાગુ નથી ...",
        noemployeesfound:"કોઈ કર્મચારી મળ્યાં નથી ...",
        filteredemployees:"ફિલ્ટર કરેલ કર્મચારી",
        name:"નામ",
        companydescription:"કંપનીનું વર્ણન",
        companystrength:"કંપનીની તાકાત",
        numberofemployees:"કર્મચારીઓની સંખ્યા",
        website:"વેબસાઇટ",
        companywebsite:"કંપની વેબસાઇટ",
        productwishlisted:"ઉત્પાદન વિશલિસ્ટેડ",
        productremovedfromwishlist:"ઉત્પાદન ઇચ્છા સૂચિમાંથી દૂર કર્યું",
        searchyourproduct:"તમારા ઉત્પાદનને શોધો",
        categories:"શ્રેણીઓ",
        seeall:"બધા જુઓ",
        featured:"ફીચર્ડ",
        bestsellers:"શ્રેષ્ઠ વેચનાર",
        mycart:"મારી ગાડી",
        favourite:"પ્રિય",
        myorders:"મારા ઓર્ડર",
        productsaved:"ઉત્પાદન સાચવ્યું",
        productunsaved:"ઉત્પાદન અસુરક્ષિત",
        noproductfound:"કોઈ ઉત્પાદન મળ્યું નથી ...",
        searchproduct:"ઉત્પાદન શોધો",
        productremovedfromcart:"કાર્ટમાંથી ઉત્પાદન કા .્યું",
        productremovefailed:"ઉત્પાદન દૂર કરવું નિષ્ફળ થયું",
        cart:"કાર્ટ",
        continue:"ચાલુ રાખો",
        allcategories:"બધા શ્રેણીઓ",
        nocategoriesfound:"કોઈ શ્રેણીઓ મળી નથી ...",
        checkout:"ચેકઆઉટ",
        number:"નંબર",
        city:"શહેર",
        subtotal:"પેટાસરવાળો",
        shipping:"વહાણ પરિવહન",
        total:"કુલ",
        buy:"ખરીદો",
        nameblank:"નામ ખાલી હોઈ શકતું નથી",
        addressblank:"સરનામું ખાલી હોઈ શકતું નથી",
        cityblank:"શહેર ખાલી હોઈ શકતું નથી",
        stateblank:"રાજ્ય ખાલી હોઈ શકતું નથી",
        postalblank:"ટપાલ કોડ ખાલી હોઈ શકતો નથી",
        phonenumberblank:"ફોન નંબર ખાલી હોઈ શકતો નથી",
        postal:"પોસ્ટ કોડ",
        phonenumber:"ફોન નંબર",
        makedefault:"ડિફોલ્ટ બનાવો",
        addaddress:"સરનામું ઉમેરો",
        updateaddress:"સરનામું અપડેટ કરો",
        productwishlistremovefailed:"વિશલિસ્ટમાંથી ઉત્પાદન દૂર કરવું નિષ્ફળ થયું",
        noproductwishlisted:"કોઈ ઉત્પાદન વિશલિસ્ટેડ નથી ...",
        noordersplacedyet:"હજી સુધી કોઈ ઓર્ડર મૂક્યા નથી ...",
        orderagain:"ફરીથી ઓર્ડર",
        notifications:"સૂચનાઓ",
        nonewnotifications:"કોઈ નવી સૂચનાઓ નથી...",
        youhavesuccessfully:"તમે સફળતાપૂર્વક છે",
        completedyourpaymentprocedure:"તમારી ચુકવણી પ્રક્રિયા પૂર્ણ કરી",
        trackorder:"ટ્રેક ઓર્ડર",
        backtohome:"ઘરે પાછા",
        productaddedtocart:"કાર્ટમાં ઉત્પાદન ઉમેર્યું",
        productalreadyaddedincart:"ઉત્પાદ પહેલેથી કાર્ટમાં ઉમેર્યું છે",
        productaddingtocartfailed:"કાર્ટમાં ઉત્પાદન ઉમેરવામાં નિષ્ફળ",
        buynow:"હમણાં જ ખરીદો",
        addtocart:"સૂચી માં સામેલ કરો",
        back:"પાછળ",
        reviews:"સમીક્ષાઓ",
        aboutthecompany:"કંપની વિશે",
        yearofestablistment:"સ્થાપના વર્ષ",
        profileupdated:"પ્રોફાઇલ અપડેટ થઈ",
        profileupdatefailed:"પ્રોફાઇલ અપડેટ નિષ્ફળ થયું",
        productdetails:"ઉત્પાદન વિગતો",
        editprofile:"પ્રોફાઇલ સંપાદિત કરો",
        shippingaddress:"પહોંચાડવાનું સરનામું",
        wishlist:"વિશસૂચિ",
        orderhistory:"ઓર્ડર ઇતિહાસ",
        paymentoption:"ચુકવણી વિકલ્પ",
        addressdeleted:"સરનામું કા .ી નાખ્યું",
        deleteaddress:"સરનામું કા Deleteી નાખો",
        wantodeleteaddress:"આ સરનામું કા deleteી નાખવા માંગો છો?",
        trackorders:"ટ્રેક ઓર્ડર",
        products:"ઉત્પાદનો",
        details:"વિગતો",






    },

}